#include "SettingsManager.hpp"
#include "Utils/StreamUtils.hpp"
#include <fstream>
#include <vector>

namespace Services {

std::string SettingsManager::getMpdConfPath() {
  std::string homeDir = getUserHomeDir();
  return homeDir + "/.config/mpd/mpd.conf";
}

std::unordered_map<std::string, std::string>
SettingsManager::parseMpdConfig(const std::string &path) {
  std::unordered_map<std::string, std::string> settings;
  std::ifstream file(path);
  if (!file.is_open()) {
    settings["auto_update"] = "yes";
    settings["restore_paused"] = "yes";
    settings["audio_output_pulse"] = "yes";
    settings["audio_output_fifo"] = "yes";
    return settings;
  }

  std::string line;
  bool inAudioBlock = false;
  std::string currentAudioType = "";

  while (std::getline(file, line)) {
    size_t first = line.find_first_not_of(" \t");
    if (first == std::string::npos)
      continue;
    if (line[first] == '#')
      continue;

    if (line.find("audio_output {") != std::string::npos ||
        (line.find("audio_output") != std::string::npos &&
         line.find('{') != std::string::npos)) {
      inAudioBlock = true;
      currentAudioType = "";
      continue;
    }

    if (inAudioBlock) {
      if (line.find('}') != std::string::npos) {
        inAudioBlock = false;
        if (currentAudioType == "pulse") {
          settings["audio_output_pulse"] = "yes";
        } else if (currentAudioType == "fifo") {
          settings["audio_output_fifo"] = "yes";
        }
        continue;
      }
      if (line.find("type") != std::string::npos) {
        if (line.find("pulse") != std::string::npos) {
          currentAudioType = "pulse";
        } else if (line.find("fifo") != std::string::npos) {
          currentAudioType = "fifo";
        }
      }
      continue;
    }

    size_t keyEnd = line.find_first_of(" \t", first);
    if (keyEnd == std::string::npos)
      continue;

    std::string key = line.substr(first, keyEnd - first);
    size_t valStart = line.find_first_not_of(" \t", keyEnd);
    if (valStart == std::string::npos)
      continue;

    std::string val = line.substr(valStart);
    size_t comment = val.find('#');
    if (comment != std::string::npos) {
      val = val.substr(0, comment);
    }
    size_t valLast = val.find_last_not_of(" \t");
    if (valLast != std::string::npos) {
      val = val.substr(0, valLast + 1);
    }

    if (val.length() >= 2 && val.front() == '"' && val.back() == '"') {
      val = val.substr(1, val.length() - 2);
    }

    settings[key] = val;
  }

  if (settings.find("auto_update") == settings.end())
    settings["auto_update"] = "yes";
  if (settings.find("restore_paused") == settings.end())
    settings["restore_paused"] = "yes";

  return settings;
}

void SettingsManager::saveMpdConfig(
    const std::string &path,
    const std::unordered_map<std::string, std::string> &settings) {
  std::ofstream file(path);
  if (!file.is_open())
    return;

  file << "# Autogenerated by HyprMusic\n\n";

  std::vector<std::string> keys = {
      "music_directory", "playlist_directory", "db_file",
      "log_file",        "pid_file",           "state_file",
      "sticker_file",    "bind_to_address",    "port",
      "restore_paused",  "auto_update"};

  for (const auto &key : keys) {
    auto it = settings.find(key);
    if (it != settings.end() && !it->second.empty()) {
      file << key << " \"" << it->second << "\"\n";
    }
  }

  auto pulseIt = settings.find("audio_output_pulse");
  if (pulseIt != settings.end() && pulseIt->second == "yes") {
    file << "\n# Audio Output for PipeWire (via Pulse plugin)\n"
         << "audio_output {\n"
         << "        type            \"pulse\"\n"
         << "        name            \"PipeWire Sound Server\"\n"
         << "}\n";
  }

  auto fifoIt = settings.find("audio_output_fifo");
  if (fifoIt != settings.end() && fifoIt->second == "yes") {
    file << "\n# Visualizer output\n"
         << "audio_output {\n"
         << "    type                    \"fifo\"\n"
         << "    name                    \"my_fifo\"\n"
         << "    path                    \"/tmp/mpd.fifo\"\n"
         << "    format                  \"44100:16:2\"\n"
         << "    always_on               \"yes\"\n"
         << "}\n";
  }
  file.close();
}

} // namespace Services
